### ISSUE TITLE
账户退出 报错

### ISSUE THREAD

**Issue by OrdinaryFish** [lulu-ls/cloud-uploader#30]
大佬你好，小工具很好用，感谢奉献。

退出登录时会报以下错误：

<img width="842" alt="image" src="https://user-images.githubusercontent.com/6408198/179343472-580203c9-caae-42b8-912f-3b3c0bd74c18.png">

`A JavaScript error occurred in the main process`

`Uncaught Exception:
TypeError: Use `delete()` to clear values
at ElectronStore.set (/Applications/cloud-uploader.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:165:19)
at Function.setLoginType (/Applications/cloud-uploader.app/Contents/Resources/app.asar/src/windows/controller/login.js:356:18)
at Function.logout (/Applications/cloud-uploader.app/Contents/Resources/app.asar/src/windows/controller/login.js:364:17)
at CloudUploader.activeLoginWindow (/Applications/cloud-uploader.app/Contents/Resources/app.asar/src/main.js:97:19)
at EventEmitter.<anonymous> (/Applications/cloud-uploader.app/Contents/Resources/app.asar/src/main.js:46:14)
at EventEmitter.emit (node:events:390:28)
at IpcMainImpl.<anonymous> (/Applications/cloud-uploader.app/Contents/Resources/app.asar/src/windows/controller/uploader.js:133:17)
at IpcMainImpl.emit (node:events:390:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)
at EventEmitter.emit (node:events:390:28)`

**Comment by lulu-ls** [comment]
感谢反馈 刚发布的 1.2.2 版本修复了一些崩溃问题，你可以下载试试

**Comment by lulu-ls** [comment]
更新试试，先关了后边如果有任何问题再提 感谢
